Make hardy init script actually background consul, create pid file, and properly chuid. Also make the start action do a little more checking

diff --git a/templates/consul.hardy.erb b/templates/consul.hardy.erb
--- a/templates/consul.hardy.erb
+++ b/templates/consul.hardy.erb
@@ -18,6 +18,7 @@ DESC="Consul service discovery framework"
 NAME=consul
 DAEMON=<%= scope.lookupvar('consul::bin_dir') %>/$NAME
 DAEMON_ARGS="agent -config-dir <%= scope.lookupvar('consul::config_dir') %> <%= scope.lookupvar('consul::extra_options') %>"
+USER=<%= scope.lookupvar('consul::user') %>
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 
@@ -43,15 +44,28 @@ do_start()
     #   0 if daemon has been started
     #   1 if daemon was already running
     #   2 if daemon could not be started
-    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+    echo "Starting consul and backgrounding"
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid $USER --background --make-pidfile --test > /dev/null \
         || return 1
-    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid $USER --background --make-pidfile -- \
         $DAEMON_ARGS \
         || return 2
 
-    # Add code here, if necessary, that waits for the process to be ready
-    # to handle requests from services started subsequently which depend
-    # on this one.  As a last resort, sleep for some time.
+    echo -n "Waiting for consul daemon to be listening..."
+    for i in `seq 1 30`; do
+        if ! start-stop-daemon --quiet --stop --test --pidfile $PIDFILE --exec $DAEMON --user $USER; then
+            echo " FAIL: consul process died"
+            return 2
+        fi
+        if "$DAEMON" info >/dev/null; then
+            echo " OK"
+            return 0
+        fi
+        echo -n .
+        sleep 1
+    done
+    echo " FAIL: consul process is alive, but is not listening."
+    return 2
 }
 
 #
@@ -59,6 +73,8 @@ do_start()
 #
 do_stop()
 {
+    # first try doing this gracefully
+    "$DAEMON" leave
     # Return
     #   0 if daemon has been stopped
     #   1 if daemon was already stopped
